### ISSUE TITLE
BUG: ne radi unos komentara

### ISSUE THREAD

**Issue by dpoldrugo** [grozdanowski/booking-for-relief-backend#10]
https://booking-for-relief.vercel.app/trazim-pomoc/2

![Screenshot_2021-01-03-11-02-16-573_com android chrome](https://user-images.githubusercontent.com/1514332/103476114-3c3c4680-4db3-11eb-9e89-4d3222995d85.jpg)

**Comment by grozdanowski** [comment]
Ispravljeno. Env varijable na Vercelu se čudno ponašaju. Fixano, a kasnije sredim i bolji fix za core issue.
