### ISSUE TITLE
Document in README.md the steps necessary to start contributing

### ISSUE THREAD

**Issue by bbozo** [grozdanowski/booking-for-relief-backend#11]
Ie

1. Install node like this
2. Using this ide import project like this
3. Start this database and create user and db with this username/pass
4. Run db migrations like this
4. You need to import these credentials here
5. Run tests, make sure they pass
6. Run dev server like this

At this point the person should be able to develop any part of the system without stupid config errors slowing them down

**Comment by grozdanowski** [comment]
Oh right, this is done  :)
