### ISSUE TITLE
Do a check of contact phone

### ISSUE THREAD

**Issue by grozdanowski** [grozdanowski/booking-for-relief-backend#16]
When someone adds an issue, they need to leave their contact phone. However there's no way for us to check whether the number is actually functional or whether that is the actual number of the person that's adding the entry.

What are the possibilities for us here?

**Comment by bbozo** [comment]
@dpoldrugo - do you have an idea :slightly_smiling_face:

**Comment by dpoldrugo** [comment]
I'm biased here because I work at Infobip: https://www.infobip.com/docs/number-lookup
https://www.infobip.com/docs/number-lookup/number-lookup-over-api

Maybe we could ask for this in a form of donation.

**Comment by grozdanowski** [comment]
_Update:_ we will use the InfoBip system to do this.

**Comment by grozdanowski** [comment]
This is a frontend issue, so I am moving the issue there.
