### ISSUE TITLE
Facebook login and relevant database footprint

### ISSUE THREAD

**Issue by bbozo** [grozdanowski/booking-for-relief-backend#3]
- [x] We want to allow facebook login/signup for everybody
- [ ] People who are reporting cases don't need to be logged in with facebook, but we want to encourage them to do so through UI design
- [ ] Operators & admins - volunteers, terrain workers, dispatchers etc need to be facebook-logged in

**Comment by grozdanowski** [comment]
@bbozo at the moment dispatchers don't need to be facebook-logged-in. We send them an invite to the admin interface, they cannot sign up themselves. This is IMHO more secure and controllable. Sounds good?

**Comment by grozdanowski** [comment]
@bbozo "People who are reporting cases don't need to be logged in with facebook, but we want to encourage them to do so through UI design" - what's the expected UX?

**Comment by bbozo** [comment]
> @bbozo at the moment dispatchers don't need to be facebook-logged-in. We send them an invite to the admin interface, they cannot sign up themselves. This is IMHO more secure and controllable. Sounds good?

True - we can link their fb accounts on first login maybe?

**Comment by bbozo** [comment]
> @bbozo "People who are reporting cases don't need to be logged in with facebook, but we want to encourage them to do so through UI design" - what's the expected UX?

Usual tricks - if I understood Tomislav - it was his idea - the login via fb button is big and blue and just works immediately, the other signup is smaller and gray and asks for name, last name, contact, ...

For start should be enough, let's see if Tomislav has any more ideas

**Comment by grozdanowski** [comment]
Volunteers cannot assign tasks to themselves without using Facebook login (and soon Google login and maybe some others). So I would say this one is done for the moment and its intended scope.
