### ISSUE TITLE
We need a tags relation on cases

### ISSUE THREAD

**Issue by bbozo** [grozdanowski/booking-for-relief-backend#5]
Tags are assigned by logged in operators and visible on the index screen. Tags would be pre-defined on system level and expanded as necessary.

We want to be able to use this to ie filter all cases that need a carpenter - or for other purposes

**Comment by grozdanowski** [comment]
Tags are added. The are not predefined but added as a string delimited by commas (`,`) in the field on the backend. Good enough for now?

**Comment by bbozo** [comment]
How much work to add a hard codes tag list and validators? ❤️

**Comment by grozdanowski** [comment]
Some. Isn't insignificant I think. Let's leave this open for now.

**Comment by grozdanowski** [comment]
@bbozo tags are now predefined in Admin. Upon entering a new case through the frontend app (or searching) you have a dropdown with autocomplete. You can still enter a custom one. You can still add multiple tags with a nice UX. I'm closing this one.
